#!/usr/bin/perl -w
# Author: Hyung Joo Lee
# Date: March 26, 2013
# This code plots the number DMRs which has p-values less than a certain value. p-values should be generated by MethylMnM.

use strict;
my $usage = '
Usage: perl $0 <input file> <output report file name>
input file: qval.bed for MM
';

die $usage unless @ARGV;

my ($in_f, $out_f) = @ARGV;
my $size_f;

my %cnt_p = ();
my %cnt_q = ();
my ($cnt_p0, $cnt_q0) = (0, 0);
open IN, "$in_f" or die "Cannot open $in_f file.\n";
while (<IN>) {
	next if /qvalue/;
	my @line = split;
	my ($pval, $qval) = ( $line[9], $line[11] );
	if ($pval == 0) {
		$cnt_p0++;
	} else {
		my $log_p = - ( (log $pval) / (log 10) );
		$log_p = int $log_p;
		$cnt_p{$log_p}++;
	}
	if ($qval == 0) {
		$cnt_q0++;
	} else {
		my $log_q = - ( (log $qval) / (log 10) );
		$log_q = int $log_q;
		$cnt_q{$log_q}++;
	}
}
close IN;

#print "cnt_p0 and cnt_q0 is $cnt_p0 and $cnt_q0.\n";

my ($max_p, $max_q) = (0, 0);
for my $key (sort keys %cnt_p) {
	$max_p = $key if ($max_p < $key);
}
for my $key (sort keys %cnt_q) {
	$max_q = $key if ($max_q < $key);
}
my $max = ($max_p > $max_q) ? $max_p : $max_q;
$cnt_p{$max} += $cnt_p0;
$cnt_q{$max} += $cnt_q0;


open REPORT, ">$out_f.report" or die "Cannot open $out_f.report file.\n";
print REPORT "-Log10(pvalue or qvalue)\t#DMRs < pvalue\t#DMRs < qvalue\n";
my @cnt_p;
my @cnt_q;
for (my $i = $max; $i >= 0; $i--) {
	$cnt_p[$i] = (exists $cnt_p{$i}) ? $cnt_p{$i} : 0;
	$cnt_q[$i] = (exists $cnt_q{$i}) ? $cnt_q{$i} : 0;
	unless ($i == $max) {
		$cnt_p[$i] += $cnt_p[$i+1];
		$cnt_q[$i] += $cnt_q[$i+1];
	}
	printf REPORT "%2d\t%10d\t%10d\n", $i, $cnt_p[$i], $cnt_q[$i];
}

close REPORT;

