#!/usr/bin/perl -w
# This converts homer location information txt file into bed file. 
# September 11, 2014
# Modified on October 7, 2015
# Author: Hyung Joo Lee

use strict;

my $usage = '
Usage: homerLocationToBed.pl $TXT.PEAK $TXT.MOTIF_LOCATION STDOUT>$BED.MOTIFS
  $TXT.PEAK:		peak.txt file generated by homer findMotifsGenome.pl
  $TXT.MOTIF_LOCATION:	outputfile.txt generated by homer findMotifsGenome.pl -find $MOTIF_FILE
  $BED.MOTIFS:		This script sends motif location as bed format to stdout.

';

die $usage unless @ARGV;

my ($peak_f, $motif_f) = @ARGV;

my %peak;
open PEAK, $peak_f or die "Cannot open $peak_f file.\n";
while (<PEAK>) {
  next if /^#/;
  my @line = split /\t/;
  $peak{$line[0]} = join ":", @line[1..3];
}
close PEAK;

open MOTIF, $motif_f or die "Cannot open $motif_f file.\n";
while (<MOTIF>) {
  next if /^PositionID/;
  chomp;
  my @line = split "\t";
  my ($chrom, $start, $end) = split ":", $peak{$line[0]};
  my ($name, $strand, $score) = @line[3..5];
  my ($chromStart, $chromEnd);
  if ($strand eq "+") {
    $chromStart = ($start+$end)/2 + $line[1] -1;
    $chromStart += 0.5 if ( ($start+$end)%2 ==1 );
    $chromEnd = $chromStart + length($line[2]);
  } else {
    $chromEnd = ($start+$end)/2 + $line[1];
    $chromEnd += 0.5 if ( ($start+$end)%2 ==1 );
    $chromStart = $chromEnd - length($line[2]);
  }
  $name .= "_$line[2]_$score";
  print join "\t", $chrom, $chromStart, $chromEnd, $name, $score, $strand;
  print "\n";
}
close MOTIF;
exit;
